name: Helloworld #workflow name
on: [push] # event
jobs: #it contsin multiple jobs
  hello: #job name
    runs-on: ubuntu-latest
    steps:
      - name: print Helloworld
        run: echo "Hello-world"